### ISSUE TITLE
Gravity Forms Encrypted Fields

### ISSUE THREAD

**Issue by neil-rowe** [lukecav/awesome-gravity-forms#1]
Gravity forms Encrypted Fields should definitely be high on this list. 
With all the data the forms collect its the only encryption plugin for gravity forms worth using.  

https://codecanyon.net/item/gravity-forms-encrypted-fields/18564931

**Comment by lukecav** [comment]
Added.
https://github.com/lukecav/awesome-gravity-forms/blob/master/README.md
