### ISSUE TITLE
GF Email validator

### ISSUE THREAD

**Issue by wpfejleszto** [lukecav/awesome-gravity-forms#12]
New GF addon:

GF Email validator - https://wpfejleszto.com/termek/gf-email-validator/

Functions:
- Real-time email validation
- Filter out disposable email addresses (16800+ email address)

Email validator must be enabled in the GF email field.

**Comment by lukecav** [comment]
https://github.com/lukecav/awesome-gravity-forms/commit/b6f19495c7e881b373817313c42f94244a2fa061
