### ISSUE TITLE
Very Useful Plugin to Add

### ISSUE THREAD

**Issue by neil-rowe** [lukecav/awesome-gravity-forms#3]
Adds super simple to use automatic options per field:  
caps/casing ,custom blacklist validation, custom text replacement, custom before/after text, link removal, HTML tag and PHP code removal

https://codecanyon.net/item/gravity-forms-auto-formatter/19513275

**Comment by lukecav** [comment]
Updated
https://github.com/lukecav/awesome-gravity-forms/blob/master/README.md
